name: changepayer_app
version: 0.0.1+1
publish_to: none
description: start your project in the fastest way
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.18.1

  get: ^4.6.6

  logger: ^2.1.0

  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.0

  dio: ^5.4.1
  flutter_launcher_icons: ^0.13.1

  # firebase
  # firebase_core: ^2.24.2
  # firebase_analytics: ^10.8.0
  # firebase_messaging: ^14.7.10
  # firebase_crashlytics: ^3.4.9

  sqflite: ^2.3.2
  hive: ^4.0.0-dev.2
  # isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.2
  # isar: ^3.1.0+1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  flutter_svg: ^2.0.10+1
  shimmer: ^3.0.0
  lottie: ^3.1.0
  auto_size_text: ^3.0.0

  flutter_dotenv: ^5.1.0
  upgrader: ^10.0.1
  adaptive_dialog: ^2.1.0
  fluttertoast: ^8.2.4
  flutter_animate: ^4.5.0
  package_info_plus: ^6.0.0
  url_launcher: ^6.2.5

  flutter_appauth: ^6.0.5

  # webview
  webview_flutter: ^4.7.0
  flutter_inappwebview: ^6.0.0

  connectivity_plus: ^6.0.1
  dropdown_button2: ^2.3.9

dev_dependencies:
  analyzer: ^6.4.1
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animation/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui/SegoeUI-Light.ttf
          weight: 300
        - asset: assets/fonts/segoeui/SegoeUI.ttf
          weight: 500
        - asset: assets/fonts/segoeui/SegoeUI-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/segoeui/SegoeUI-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
