name: changepayer_app
version: 0.0.1+3
publish_to: none
description: start your project in the fastest way
environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  get: ^4.7.2

  logger: ^2.5.0

  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.5

  dio: ^5.8.0+1
  flutter_launcher_icons: ^0.14.3

  # firebase
  # firebase_core: ^2.24.2
  # firebase_analytics: ^10.8.0
  # firebase_messaging: ^14.7.10
  # firebase_crashlytics: ^3.4.9

  path_provider: ^2.1.5
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.2
  flutter_secure_storage: ^9.2.4

  flutter_svg: ^2.0.17
  shimmer: ^3.0.0
  lottie: ^3.3.1
  auto_size_text: ^3.0.0

  flutter_dotenv: ^5.2.1
  adaptive_dialog: ^2.4.0
  fluttertoast: ^8.2.12
  flutter_animate: ^4.5.2
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1

  # webview
  webview_flutter: ^4.10.0
  flutter_inappwebview: ^6.1.5

  connectivity_plus: ^6.1.3
  dropdown_button2: ^2.3.9

  nfc_manager: ^3.5.0
  qr_flutter: ^4.1.0
  qr_code_dart_scan: ^0.9.11

dev_dependencies:
  analyzer: any
  build_runner: any
  flutter_lints: any
  json_serializable: any

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animation/
    - assets/icons/
    - assets/fonts/
    - assets/

  fonts:
    - family: SegoeUI
      fonts:
        - asset: assets/fonts/segoeui/SegoeUI-Light.ttf
          weight: 300
        - asset: assets/fonts/segoeui/SegoeUI.ttf
          weight: 500
        - asset: assets/fonts/segoeui/SegoeUI-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/segoeui/SegoeUI-Bold.ttf
          weight: 700
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/ubuntu/Ubuntu-Bold.ttf
          weight: 700
